### ISSUE TITLE
DataSource user is null? in sbt console

### ISSUE THREAD

**Issue by AmirHo3ein13** [payintech/play-ebean#13]
I'm trying to test my model and queries in `sbt console`, but when I run a query like `models.MyModel.finder.all()`, this exception happens:
```
io.ebean.datasource.DataSourceConfigurationException: Configuration error creating DataSource for the default Database. This typically means a missing application-test.yaml or missing ebean-test-config dependency. See https://ebean.io/docs/trouble-shooting#datasource
  at io.ebean.Ebean$ServerManager.<init>(Ebean.java:85)
  at io.ebean.Ebean$ServerManager.<init>(Ebean.java:48)
  at io.ebean.Ebean.<clinit>(Ebean.java:43)
  at io.ebean.DB.byName(DB.java:85)
  at io.ebean.Finder.db(Finder.java:121)
  at io.ebean.Finder.query(Finder.java:200)
  at io.ebean.Finder.all(Finder.java:169)
  ... 36 elided
Caused by: io.ebean.datasource.DataSourceConfigurationException: DataSource user is null?
  at io.ebean.datasource.pool.ConnectionPool.<init>(ConnectionPool.java:227)
  at io.ebean.datasource.core.Factory.createPool(Factory.java:15)
  at io.ebeaninternal.server.core.DefaultContainer.getDataSourceFromConfig(DefaultContainer.java:273)
  at io.ebeaninternal.server.core.DefaultContainer.setDataSource(DefaultContainer.java:217)
  at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:103)
  at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:69)
  at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:35)
  at io.ebean.EbeanServerFactory.create(EbeanServerFactory.java:58)
  at io.ebean.Ebean$ServerManager.getWithCreate(Ebean.java:126)
  at io.ebean.Ebean$ServerManager.<init>(Ebean.java:75)
  ... 42 more
```
But when I run the server using `sbt run` or `sbt runProd`, there isn't any problem!  
My configuration for ebean is:
```
## Ebean
# https://github.com/payintech/play-ebean
# ~~~~~
ebean {
  servers {

    # You can declare as many servers as you want.
    # By convention, the default server is named `default`
    default {

      # Locations of the classes to enhance
      enhancement = ["models.*"]

      # Extra server settings
      settings {

        # Set to true if this server is Document store only
        onlyUseDocStore = false

        # Set to true to quote all fields (useful if you use
        # reserved keywords as field names)
        allQuotedIdentifiers = false

        # Set to true to disable L2 caching. Typically useful in performance testing
        disableL2Cache = false

        # Encryption key manager to use for fields annotated with @Encrypted
        # encryptKeyManager = "com.zero_x_baadf00d.ebean.encryption.StandardEncryptKeyManager"

        # Set the user provider. This is used to populate @WhoCreated, @WhoModified an
        # support other audit features
        # currentUserProvider = "com.zero_x_baadf00d.ebean.provider.CustomUserProvider"

        # Set the tenant provider
        # currentTenantProvider = "com.zero_x_baadf00d.ebean.provider.CustomTenantProvider"
      }



      # Extra Ebean server configuration
      # Use full classpath (ie: ebean.DemoEbeanServerExtraConfig)
      extra-config = [
      ]
    }
  }

  # Ebean DB Migration
  # Read more at https://github.com/ebean-orm/ebean-dbmigration
  dbmigration {

    # Is Ebean DB Migration enabled?
    enabled = true

    # Defines where are located migration SQL scripts. Ebean DB Migration
    # will search SQL scripts in "conf/${migrationPath}/${serverName}-${appMode}"
    # or "conf/${migrationPath}/${serverName}"
    #
    # By example, in your run your application in development mode:
    #     conf/dbmigration/<platform>/default-dev/
    #  OR conf/dbmigration/<platform>/default/
    #  OR conf/dbmigration/default-dev/
    #  OR conf/dbmigration/default/
    migrationPath = "migrations"

    # Is the migration must be auto applied?
    autoApply = true

    # Override the platform name detection
    # https://github.com/ebean-orm/ebean-migration/blob/master/src/main/java/io/ebean/migration/DbPlatformNames.java
    platformName = null
  }
}
```
And dependencies are:
```
libraryDependencies ++= Seq(
  "org.xerial" % "sqlite-jdbc" % "3.30.1",
  "com.payintech" %% "play-ebean" % "19.10",
  "io.ebean" % "ebean-test" % "12.1.10" % Test,
  "io.ebean.test" % "ebean-test-config" % "11.41.2" % Test
)
```

**Comment by PierreAdam** [comment]
Hello,

I just gave it a try, for me it does work properly after following the PlayFramework documentation about how to properly load a project using sbt console. Please refer to the following page : https://www.playframework.com/documentation/2.8.x/PlayConsole#Launch-the-Scala-console

You will need to at least run those commands in order to properly load the Play Ebean module : 

``` scala
import play.api._
val env     = Environment(new java.io.File("."), this.getClass.getClassLoader, Mode.Dev)
val context = ApplicationLoader.Context.create(env)
val loader  = ApplicationLoader(context)
val app     = loader.load(context)
```

You should then be able to request your models.

Just a quick thing about [play evolution](https://www.playframework.com/documentation/2.8.x/Evolutions), this will by default be disabled when starting from sbt console. In order to enable it, you should be able to put it explicitly on your `application.conf`

```
play.evolutions {
    db.default.enabled = true
    db.default.useLocks = true
    db.default.autoApply = true
    db.default.autoApplyDowns = false
}
```
