### ISSUE TITLE
ClassNotFoundException: ElasticDocumentStore

### ISSUE THREAD

**Issue by Hospes** [payintech/play-ebean#6]
Hi there, thanks for this fork! But I can't get it work well, when I'm trying to run project I see runtime exception:

```
play.db.ebean.orm.DefaultEbeanConfig$EbeanConfigParser$1: Configuration error[io.ebeanservice.elastic.ElasticDocumentStore]
	at play.db.ebean.orm.DefaultEbeanConfig$EbeanConfigParser.throwConfigurationException(DefaultEbeanConfig.java:125)
	at play.db.ebean.orm.DefaultEbeanConfig$EbeanConfigParser.lambda$parse$1(DefaultEbeanConfig.java:302)
	at java.util.HashMap$KeySet.forEach(HashMap.java:933)
	at play.db.ebean.orm.DefaultEbeanConfig$EbeanConfigParser.parse(DefaultEbeanConfig.java:200)
	at play.db.ebean.orm.DefaultEbeanConfig$EbeanConfigParser.get(DefaultEbeanConfig.java:113)
	at play.db.ebean.orm.DefaultEbeanConfig$EbeanConfigParser.get(DefaultEbeanConfig.java:78)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
	at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:72)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
	at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:62)
Caused by: java.lang.ClassNotFoundException: io.ebeanservice.elastic.ElasticDocumentStore
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at play.db.ebean.orm.DefaultEbeanConfig$EbeanConfigParser.lambda$parse$1(DefaultEbeanConfig.java:297)
	at java.util.HashMap$KeySet.forEach(HashMap.java:933)
	at play.db.ebean.orm.DefaultEbeanConfig$EbeanConfigParser.parse(DefaultEbeanConfig.java:200)
	at play.db.ebean.orm.DefaultEbeanConfig$EbeanConfigParser.get(DefaultEbeanConfig.java:113)
	at play.db.ebean.orm.DefaultEbeanConfig$EbeanConfigParser.get(DefaultEbeanConfig.java:78)
```

my application.config looks like that:
```
ebean.servers.default.enhancement = ["db.*"]
ebean.servers.default.docstore.url="http://127.0.0.1:9200"
ebean.servers.default.docstore.active=true
ebean.servers.default.docstore.generateMapping=true
ebean.servers.default.docstore.dropCreate=true
ebean.servers.default.docstore.pathToResources="conf"
```

Maybe you have some thoughts about that ?
What can I do wrong?
I'm using the latest plugin:
```
addSbtPlugin("com.payintech" % "sbt-play-ebean" % "18.05")
```

**Comment by thibaultmeyer** [comment]
Hello,

which version of `ebean-elastic` are you using ou your `build.sbt` file? Our testing project use `"io.ebean" % "ebean-elastic" % "11.15.2"`
