### ISSUE TITLE
Support JDK 11

### ISSUE THREAD

**Issue by almothafar** [payintech/play-ebean#7]
Currently, I'm getting error "Unsupported class file major version 55", the problem solved in ebean-agent version 11.24.1 (https://github.com/ebean-orm/ebean-agent/issues/82) so I thought it is enough to just release a version with the latest updates from ebean.

```
libraryDependencies ++= Seq(
  "io.ebean" % "ebean" % "11.26.1",
  "io.ebean" % "ebean-agent" % "11.26.1",
  "io.ebean" % "ebean-migration" % "11.11.1"
)

dependencyOverrides ++= Seq(
  "io.ebean" % "ebean" % "11.26.1",
  "io.ebean" % "ebean-agent" % "11.26.1",
  "io.ebean" % "ebean-migration" % "11.11.1"
)
```

Didn't work, do you have any idea?

Full exception: 

```
java.lang.IllegalArgumentException: Unsupported class file major version 55
        at io.ebean.enhance.asm.ClassReader.<init>(ClassReader.java:166)
        at io.ebean.enhance.asm.ClassReader.<init>(ClassReader.java:148)
        at io.ebean.enhance.asm.ClassReader.<init>(ClassReader.java:136)
        at io.ebean.enhance.Transformer.detect(Transformer.java:353)
        at io.ebean.enhance.Transformer.enhanceEntityAndTransactional(Transformer.java:188)
        at io.ebean.enhance.Transformer.transform(Transformer.java:153)
        at io.ebean.enhance.common.InputStreamTransform.transform(InputStreamTransform.java:57)
        at io.ebean.enhance.common.InputStreamTransform.transform(InputStreamTransform.java:41)
        at io.ebean.enhance.ant.OfflineFileTransform.transformFile(OfflineFileTransform.java:149)
        at io.ebean.enhance.ant.OfflineFileTransform.processPackage(OfflineFileTransform.java:133)
        at io.ebean.enhance.ant.OfflineFileTransform.process(OfflineFileTransform.java:102)
        at io.ebean.enhance.ant.OfflineFileTransform.process(OfflineFileTransform.java:71)
        at play.ebean.sbt.PlayEbean$.$anonfun$ebeanEnhance$1(PlayEbean.scala:80)
        at scala.Function1.$anonfun$compose$1(Function1.scala:44)
        at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:67)
        at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
        at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
        at sbt.Execute.work(Execute.scala:278)
        at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
        at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
java.lang.IllegalArgumentException: Unsupported class file major version 55
        at io.ebean.enhance.asm.ClassReader.<init>(ClassReader.java:166)
        at io.ebean.enhance.asm.ClassReader.<init>(ClassReader.java:148)
        at io.ebean.enhance.asm.ClassReader.<init>(ClassReader.java:136)
        at io.ebean.enhance.Transformer.detect(Transformer.java:353)
        at io.ebean.enhance.Transformer.enhanceEntityAndTransactional(Transformer.java:188)
        at io.ebean.enhance.Transformer.transform(Transformer.java:153)
        at io.ebean.enhance.common.InputStreamTransform.transform(InputStreamTransform.java:57)
        at io.ebean.enhance.common.InputStreamTransform.transform(InputStreamTransform.java:41)
        at io.ebean.enhance.ant.OfflineFileTransform.transformFile(OfflineFileTransform.java:149)
        at io.ebean.enhance.ant.OfflineFileTransform.processPackage(OfflineFileTransform.java:133)
        at io.ebean.enhance.ant.OfflineFileTransform.process(OfflineFileTransform.java:102)
        at io.ebean.enhance.ant.OfflineFileTransform.process(OfflineFileTransform.java:71)
        at play.ebean.sbt.PlayEbean$.$anonfun$ebeanEnhance$1(PlayEbean.scala:80)
        at scala.Function1.$anonfun$compose$1(Function1.scala:44)
        at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:67)
        at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
        at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
        at sbt.Execute.work(Execute.scala:278)
        at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
        at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
java.lang.IllegalArgumentException: Unsupported class file major version 55
        at io.ebean.enhance.asm.ClassReader.<init>(ClassReader.java:166)
        at io.ebean.enhance.asm.ClassReader.<init>(ClassReader.java:148)
        at io.ebean.enhance.asm.ClassReader.<init>(ClassReader.java:136)
        at io.ebean.enhance.Transformer.detect(Transformer.java:353)
        at io.ebean.enhance.Transformer.enhanceEntityAndTransactional(Transformer.java:188)
        at io.ebean.enhance.Transformer.transform(Transformer.java:153)
        at io.ebean.enhance.common.InputStreamTransform.transform(InputStreamTransform.java:57)
        at io.ebean.enhance.common.InputStreamTransform.transform(InputStreamTransform.java:41)
        at io.ebean.enhance.ant.OfflineFileTransform.transformFile(OfflineFileTransform.java:149)
        at io.ebean.enhance.ant.OfflineFileTransform.processPackage(OfflineFileTransform.java:133)
        at io.ebean.enhance.ant.OfflineFileTransform.process(OfflineFileTransform.java:102)
        at io.ebean.enhance.ant.OfflineFileTransform.process(OfflineFileTransform.java:71)
        at play.ebean.sbt.PlayEbean$.$anonfun$ebeanEnhance$1(PlayEbean.scala:80)
        at scala.Function1.$anonfun$compose$1(Function1.scala:44)
        at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:67)
        at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
        at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
        at sbt.Execute.work(Execute.scala:278)
        at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
        at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
java.lang.IllegalArgumentException: Unsupported class file major version 55
        at io.ebean.enhance.asm.ClassReader.<init>(ClassReader.java:166)
        at io.ebean.enhance.asm.ClassReader.<init>(ClassReader.java:148)
        at io.ebean.enhance.asm.ClassReader.<init>(ClassReader.java:136)
        at io.ebean.enhance.Transformer.detect(Transformer.java:353)
        at io.ebean.enhance.Transformer.enhanceEntityAndTransactional(Transformer.java:188)
        at io.ebean.enhance.Transformer.transform(Transformer.java:153)
        at io.ebean.enhance.common.InputStreamTransform.transform(InputStreamTransform.java:57)
        at io.ebean.enhance.common.InputStreamTransform.transform(InputStreamTransform.java:41)
        at io.ebean.enhance.ant.OfflineFileTransform.transformFile(OfflineFileTransform.java:149)
        at io.ebean.enhance.ant.OfflineFileTransform.processPackage(OfflineFileTransform.java:133)
        at io.ebean.enhance.ant.OfflineFileTransform.process(OfflineFileTransform.java:102)
        at io.ebean.enhance.ant.OfflineFileTransform.process(OfflineFileTransform.java:71)
        at play.ebean.sbt.PlayEbean$.$anonfun$ebeanEnhance$1(PlayEbean.scala:80)
        at scala.Function1.$anonfun$compose$1(Function1.scala:44)
        at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:67)
        at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
        at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
        at sbt.Execute.work(Execute.scala:278)
        at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
        at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
java.lang.IllegalArgumentException: Unsupported class file major version 55
        at io.ebean.enhance.asm.ClassReader.<init>(ClassReader.java:166)
        at io.ebean.enhance.asm.ClassReader.<init>(ClassReader.java:148)
        at io.ebean.enhance.asm.ClassReader.<init>(ClassReader.java:136)
        at io.ebean.enhance.Transformer.detect(Transformer.java:353)
        at io.ebean.enhance.Transformer.enhanceEntityAndTransactional(Transformer.java:188)
        at io.ebean.enhance.Transformer.transform(Transformer.java:153)
        at io.ebean.enhance.common.InputStreamTransform.transform(InputStreamTransform.java:57)
        at io.ebean.enhance.common.InputStreamTransform.transform(InputStreamTransform.java:41)
        at io.ebean.enhance.ant.OfflineFileTransform.transformFile(OfflineFileTransform.java:149)
        at io.ebean.enhance.ant.OfflineFileTransform.processPackage(OfflineFileTransform.java:133)
        at io.ebean.enhance.ant.OfflineFileTransform.process(OfflineFileTransform.java:102)
        at io.ebean.enhance.ant.OfflineFileTransform.process(OfflineFileTransform.java:71)
        at play.ebean.sbt.PlayEbean$.$anonfun$ebeanEnhance$1(PlayEbean.scala:80)
        at scala.Function1.$anonfun$compose$1(Function1.scala:44)
        at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:67)
        at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
        at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
        at sbt.Execute.work(Execute.scala:278)
        at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
        at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by almothafar** [comment]
The overrides worked in **plugins.sbt** not as mentioned in README in **build.sbt**.

**Comment by thibaultmeyer** [comment]
Hello,

thank you for reporting this issue. All ebean dependences have been updated to latest version in the commit 77b155833652171955725287a0a4dd96cc4e6bf3. A new version of the plugin will be soon published.

**Comment by almothafar** [comment]
The commit mentioned is about agent 11.11.1 while the fix pushed in 11.24.1, and I think 18.10 already pushed and I'm using it already.

https://github.com/ebean-orm/ebean-agent/releases

For ASK I remember the fix pushed to 7.0.0 and 6.2.1 the current version of ebean-agent (in 18.10) using 6.1.1.

**Comment by thibaultmeyer** [comment]
Yes, refresh your page, the commit number is the right (77b155833652171955725287a0a4dd96cc4e6bf3)...

```
 Upgrade dependencies

  - ebean (io.ebean) from 11.22.10 to 11.26.1
  - ebean-agent (io.ebean) from 11.11.1 to 11.26.1
  - ebean-migration (io.ebean) from 11.9.1 to 11.11.1
```

**Comment by thibaultmeyer** [comment]
The new version has just been published. She will be available in a few minutes.
