### ISSUE TITLE
Version 18.12 fails with Java 11 

### ISSUE THREAD

**Issue by novakov-alexey-zz** [payintech/play-ebean#9]
Trying to start my Play application with Java 11:

plugin.sbt:
```
addSbtPlugin("com.payintech" % "sbt-play-ebean" % "18.12")
```

java --version
```
openjdk 11.0.1 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)
```

```
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2218)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4147)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4151)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5140)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5146)
	at com.google.inject.internal.util.StackTraceElements.forMember(StackTraceElements.java:70)
	at com.google.inject.internal.Errors.formatSource(Errors.java:817)
	at com.google.inject.internal.Errors.formatSource(Errors.java:796)
	at com.google.inject.internal.Errors.formatInjectionPoint(Errors.java:849)
	at com.google.inject.internal.Errors.formatSource(Errors.java:811)
Caused by: java.lang.IllegalArgumentException: null
	at com.google.inject.internal.asm.$ClassReader.<init>(Unknown Source)
	at com.google.inject.internal.asm.$ClassReader.<init>(Unknown Source)
	at com.google.inject.internal.asm.$ClassReader.<init>(Unknown Source)
	at com.google.inject.internal.util.LineNumbers.<init>(LineNumbers.java:66)
	at com.google.inject.internal.util.StackTraceElements$1.load(StackTraceElements.java:46)
	at com.google.inject.internal.util.StackTraceElements$1.load(StackTraceElements.java:43)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3708)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2416)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2299)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2212)
```

One more exception is afterwards:

```
java.lang.NoClassDefFoundError: Could not initialize class io.ebean.Ebean
	at io.ebean.Finder.db(Finder.java:116)
	at io.ebean.Finder.query(Finder.java:196)
        ......
```

**Comment by thibaultmeyer** [comment]
Hello,

Currently, Play Framework don't officially support Java 9, 10 or 11. It working with some versions, but not out of the box. Do you have tried the solution from the ticket https://github.com/payintech/play-ebean/issues/8 ?

**Comment by novakov-alexey-zz** [comment]
@0xbaadf00d do you mean to add missing dependencies? If - yes, then I've tried that, but It didn't help.

P.S. I've updated initial comment with one more exception which is thrown in a couple of seconds as well.

**Comment by thibaultmeyer** [comment]
Could you try to run the command `sbt clean` and `sbt update` ? What is the ouput of the `sbt update` command ? which version of Play are you using ?

**Comment by novakov-alexey-zz** [comment]
```
$ update
[info] Updating ...
[info] Done updating.
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
```

Play version is:

```
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.6.20")
```

**Comment by thibaultmeyer** [comment]
Hello, I try to reproduce this issue on an new Play java project (sbt new ...). But I can't, everything run without any error.  Could you show your configuration for this plugin ?

**Comment by novakov-alexey-zz** [comment]
It seems I found workaround which works now on Java11. Have to switch to original plugin and override dependencies to have latest Ebean:

```
addSbtPlugin("com.typesafe.sbt" % "sbt-play-ebean" % "4.1.3")

dependencyOverrides ++= Seq(
  "io.ebean" % "ebean" % "11.31.1",
  "io.ebean" % "ebean-agent" % "11.27.1",
  "io.ebean" % "ebean-migration" % "11.13.1"
)
```

application.conf:

```
ebean.default = ["models.*"]

play.evolutions.db.default.autoApply=false

play.evolutions.enabled=true
play.evolutions.enabled=${?PLAY_EVOLUTIONS}
```

**Comment by thibaultmeyer** [comment]
Oh I think understanding what going wrong, for the needs of our plugin (docstore, dbmigration, ...), we have changed all configuration keys. It's probably for that you can't run your project with it. Please check the README file to have the new structure

**Comment by novakov-alexey-zz** [comment]
Thanks for your help, I will try to check the new keys.
